In [ ]:
# Import torch
import torch
from torch import nn # nn contains all of PyTorch's building blocks for neural networks
import matplotlib.pyplot as plt

# Check PyTorch version
torch.__version__

# Create random tensor
A = torch.rand(size=(7, 7))
A, A.dtype


(tensor([[0.1502, 0.8061, 0.5986, 0.6137, 0.4944, 0.4821, 0.8980],
         [0.8783, 0.3096, 0.6928, 0.5916, 0.2240, 0.8532, 0.4727],
         [0.2291, 0.8146, 0.3765, 0.1101, 0.1087, 0.9415, 0.2471],
         [0.5472, 0.3917, 0.2688, 0.2406, 0.0840, 0.4176, 0.3971],
         [0.9735, 0.8745, 0.2873, 0.5344, 0.9074, 0.6754, 0.6346],
         [0.3491, 0.4104, 0.9237, 0.3811, 0.7717, 0.6615, 0.1049],
         [0.7959, 0.7807, 0.5776, 0.8842, 0.0560, 0.4856, 0.9978]]),
 torch.float32)

In [ ]:
# Create another random tensor
B = torch.rand(size=(1, 7))
print(B, B.dtype)

print(50*'##')
# Perform matrix multiplication
torch.matmul(B,A)

tensor([[0.1893, 0.6818, 0.2158, 0.2395, 0.8381, 0.6659, 0.2805]]) torch.float32
####################################################################################################


tensor([[2.0793, 1.8585, 1.7492, 1.5506, 1.5800, 2.1190, 1.5223]])

In [ ]:
# Set manual seed

torch.manual_seed(0)



# Create two random tensors
A = torch.rand(7, 7)
B = torch.rand(1, 7)


# Matrix multiply tensors

result = torch.matmul(A, B.T)

print(result, result.shape)


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])


In [ ]:

torch.cuda.manual_seed(1234)

if torch.cuda.is_available():
    device = "cuda"
elif torch.backends.mps.is_available():
    device = "mps"
else:
    device = "cpu"


print(device)


cuda


In [ ]:
torch.manual_seed(1234)

# # Set random seed

tensor1 = torch.rand(2, 3)
tensor2 = torch.rand(2, 3)

# # Check for access to GPU

if torch.cuda.is_available():
    device = torch.device("cuda")
    tensor1 = tensor1.to(device)
    tensor2 = tensor2.to(device)
    print("Device:", device)
else:
    device = torch.device("cpu")
    print(" CUDA not available, using CPU")
# Create two random tensors on GPU

print(tensor1, tensor2)



Device: cuda
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0') tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')


In [ ]:
# Perform matmul on tensor_A and tensor_B

tensor2_T = tensor2.T

result = torch.matmul(tensor1, tensor2_T)

print(result, result.shape)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0') torch.Size([2, 2])


In [ ]:
# Find max
print(f"Minimum: {result.min()}")
# Find min
print(f"Maximum: {result.max()}")



Minimum: 0.3647301495075226
Maximum: 0.5617256760597229


In [ ]:
# Find arg max
print(f"Index where max value occurs: {result.argmax()}")
#Find arg min
print(f"Index where min value occurs: {result.argmin()}")

Index where max value occurs: 3
Index where min value occurs: 0


In [ ]:
# Set seed
torch.manual_seed(7)

# Create random tensor

tensor = torch.rand(1, 1, 1, 10)
print(tensor, tensor.shape)
# Remove single dimensions
tensor_squeezed = tensor.squeeze()

# Print out tensors and their shapes
print(tensor_squeezed, tensor_squeezed.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
